# Generated by Django 5.2.7 on 2025-10-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightgoal",
            name="pace",
            field=models.CharField(
                choices=[
                    ("slow", "Slow (0.3 kg/week)"),
                    ("moderate", "Moderate (0.5 kg/week)"),
                    ("fast", "Fast (1.0 kg/week)"),
                ],
                default="moderate",
                max_length=10,
            ),
        ),
    ]
